# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 195f22c77897c1bdc5fb5a7a36ac9f377d7468f55a1189ed18ec4b553c17769d78a87f91a1f8b3b1baa1c5b598f5101415819d652d10225c4b2433ac62cf7ad9

test:
  secret_key_base: 3d1b0c71b5ffbe7f344878ad63b947088ce7df436e8bc9736e35633d9a11e944537c710252c57a017672f26f72f0693e0bdfa7a64c1cc216a5f3c340a00c471a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
